version: 0.2

phases:
  install:
    commands:
      - ls
      - npm install -g serverless
  build:
    commands:
      - npm install --only=dev
  post_build:
    commands:
      - serverless deploy --stage dev --package 4266-MyCertification-sls-pkg-dev --force
